
CREATE TABLE board (
    id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 순번
    code NUMBER(11) NOT NULL, -- 게시물 구분 코드
    title NVARCHAR2(1000) NOT NULL, -- 제목
    content CLOB, -- 내용
    start_date date default null, -- 시작일
    end_date date default null, -- 종료일
    reg_id VARCHAR2(30) NOT NULL, -- 등록 id
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 등록일
    mod_id VARCHAR2(30), -- 수정 id
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 수정일
);

CREATE TABLE upload_file (
    id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 파일 id
    file_target VARCHAR2(20) NOT NULL, -- 파일 대상
    file_name VARCHAR2(1000), -- 파일명
    save_file_name VARCHAR2(255) NOT NULL, -- 저장된 파일명
    file_path VARCHAR2(255), -- full 파일경로
    file_dir VARCHAR2(255), -- 파일경로
    content_type VARCHAR2(100), -- 파일 타입
    file_size NUMBER(20), -- 파일 크기
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 등록일
);


CREATE TABLE file_map (
    id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- id
    board_id NUMBER(20) NOT NULL, -- 게시물 id
    file_id NUMBER(20) NOT NULL, -- 파일 id
    CONSTRAINT fk_board_id FOREIGN KEY (board_id) REFERENCES board(id), -- 외래키 제약조건
    CONSTRAINT fk_upload_file_id FOREIGN KEY (file_id) REFERENCES upload_file(id) -- 외래키 제약조건
);


CREATE TABLE MENU (
    seq         NUMBER(10)                          -- 정렬순서
    , role_user   NUMBER(1) DEFAULT 0                 -- USER 권한 (bit 대체)
    , role_admin  NUMBER(1) DEFAULT 0                 -- ADMIN 권한
    , id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY              -- unsigned int -> NUMBER(10)
    , depth       NUMBER(10) DEFAULT 0 NOT NULL       -- Menu depth
    , role_id     NUMBER(10) DEFAULT 0 NOT NULL       -- 메뉴권한
    , menu_icon   VARCHAR2(255)                       -- 메뉴 아이콘
    , menu_link   VARCHAR2(255)                       -- 메뉴 링크
    , menu_name   VARCHAR2(255) NOT NULL              -- 메뉴 명
    , parent_id   NUMBER(10) DEFAULT NULL             -- 부모 메뉴 id
    , is_active   NUMBER(1) DEFAULT 0 NOT NULL        -- 사용여부
    , role_system NUMBER(1) DEFAULT 0                 -- System 권한
);

COMMENT ON TABLE MENU IS '메뉴';
COMMENT ON COLUMN MENU.seq IS '정렬순서';
COMMENT ON COLUMN MENU.role_user IS 'USER 권한';
COMMENT ON COLUMN MENU.role_admin IS 'ADMIN 권한';
COMMENT ON COLUMN MENU.id IS 'Primary key';
COMMENT ON COLUMN MENU.depth IS 'Menu depth';
COMMENT ON COLUMN MENU.role_id IS '메뉴권한';
COMMENT ON COLUMN MENU.menu_icon IS '메뉴 아이콘';
COMMENT ON COLUMN MENU.menu_link IS '메뉴 링크';
COMMENT ON COLUMN MENU.menu_name IS '메뉴 명';
COMMENT ON COLUMN MENU.parent_id IS '부모 메뉴 id';
COMMENT ON COLUMN MENU.is_active IS '사용여부';
COMMENT ON COLUMN MENU.role_system IS 'System 권한';