INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_USER');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_SYSTEM');

INSERT INTO SCOTT.MENU (SEQ,ROLE_USER,ROLE_ADMIN,"DEPTH",ROLE_ID,MENU_ICON,MENU_LINK,MENU_NAME,PARENT_ID,IS_ACTIVE,ROLE_SYSTEM) VALUES
(0,0,1,1,2,'DashboardIcon','/admin/dashboard','대시보드',NULL,1,1);
INSERT INTO SCOTT.MENU (SEQ,ROLE_USER,ROLE_ADMIN,"DEPTH",ROLE_ID,MENU_ICON,MENU_LINK,MENU_NAME,PARENT_ID,IS_ACTIVE,ROLE_SYSTEM) VALUES
(100,0,1,1,2,NULL,NULL,'게시물 관리',NULL,1,1);
INSERT INTO SCOTT.MENU (SEQ,ROLE_USER,ROLE_ADMIN,"DEPTH",ROLE_ID,MENU_ICON,MENU_LINK,MENU_NAME,PARENT_ID,IS_ACTIVE,ROLE_SYSTEM) VALUES
(101,0,1,2,2,'InfoIcon','/admin/notice','공지사항',2,1,1);
